language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.36.0
matrix:
  include:
    - rust: stable # not locked down or consistent, since allow_failures
      env: RUSTFMT
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check
  allow_failures:
    - rust: nightly
    - env: RUSTFMT
script: cargo test --release --verbose --all
